import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<div className="w-full md:px-20 pt-10 px-6">{children}</div>
			</body>
		</html>
	);
}
