import "./globals.css";
import "./globals.css";
import { PT_Serif } from "next/font/google";
import { DM_Sans } from "next/font/google";

const ptSerif = PT_Serif({
	subsets: ["latin"], // include ce subseturi vrei
	weight: ["400", "700"], // specifică greutăţile folosite
	display: "swap",
});
const dmSans = DM_Sans({
	subsets: ["latin"], // include ce subseturi vrei
	weight: ["400", "500", "700"], // specifică greutăţile folosite
	display: "swap",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<div className="w-full md:px-20 pt-10 px-6">{children}</div>
			</body>
		</html>
	);
}
export { dmSans };
export { ptSerif };
